import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../providers/auth_provider.dart';
import '../../providers/mood_provider.dart';
import '../../providers/user_provider.dart';
import '../../../domain/entities/mood_log.dart';

class MoodCheckInScreen extends ConsumerStatefulWidget {
  const MoodCheckInScreen({super.key});

  @override
  ConsumerState<MoodCheckInScreen> createState() => _MoodCheckInScreenState();
}

class _MoodCheckInScreenState extends ConsumerState<MoodCheckInScreen> {
  final _noteController = TextEditingController();
  final List<String> _availableTags = [
    'Anxious',
    'Stressed',
    'Calm',
    'Happy',
    'Sad',
    'Energetic',
    'Tired',
    'Grateful',
    'Overwhelmed',
    'Peaceful',
  ];

  @override
  void dispose() {
    _noteController.dispose();
    super.dispose();
  }

  Future<void> _saveMoodLog() async {
    final userId = ref.read(currentUserIdProvider);
    if (userId == null) return;

    final moodScore = ref.read(currentMoodScoreProvider);
    final tags = ref.read(currentMoodTagsProvider);
    final note = _noteController.text.trim();

    final moodLog = MoodLog(
      id: '', // Will be generated by Firestore
      userId: userId,
      moodScore: moodScore,
      createdAt: DateTime.now(),
      tags: tags,
      note: note.isNotEmpty ? note : null,
      source: 'manual',
    );

    try {
      await ref.read(moodNotifierProvider.notifier).createMoodLog(moodLog);
      
      // Update user streak and check-in count
      await ref.read(userNotifierProvider.notifier).incrementTotalCheckIns(userId);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Mood logged successfully!'),
            duration: Duration(seconds: 2),
          ),
        );
        
        // Reset form
        ref.read(currentMoodScoreProvider.notifier).state = 3;
        ref.read(currentMoodTagsProvider.notifier).state = [];
        ref.read(currentMoodNoteProvider.notifier).state = '';
        _noteController.clear();
        
        // Go back or to mood history
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error logging mood: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final moodScore = ref.watch(currentMoodScoreProvider);
    final selectedTags = ref.watch(currentMoodTagsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('How are you feeling?'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => context.pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Mood emoji display
            Container(
              padding: const EdgeInsets.symmetric(vertical: 32, horizontal: 24),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    _getMoodColor(moodScore, theme).withOpacity(0.1),
                    _getMoodColor(moodScore, theme).withOpacity(0.05),
                  ],
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                ),
                borderRadius: BorderRadius.circular(20),
              ),
              child: Column(
                children: [
                  Text(
                    _getMoodEmoji(moodScore),
                    style: const TextStyle(fontSize: 100),
                  ),
                  const SizedBox(height: 12),
                  Text(
                    _getMoodLabel(moodScore),
                    style: theme.textTheme.headlineSmall?.copyWith(
                      fontWeight: FontWeight.bold,
                      color: _getMoodColor(moodScore, theme),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 32),
            
            // Mood scale slider
            Text(
              'Rate your mood',
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            SliderTheme(
              data: SliderTheme.of(context).copyWith(
                activeTrackColor: _getMoodColor(moodScore, theme),
                inactiveTrackColor: _getMoodColor(moodScore, theme).withOpacity(0.2),
                thumbColor: _getMoodColor(moodScore, theme),
                overlayColor: _getMoodColor(moodScore, theme).withOpacity(0.2),
                trackHeight: 6,
              ),
              child: Slider(
                value: moodScore.toDouble(),
                min: 1,
                max: 5,
                divisions: 4,
                label: moodScore.toString(),
                onChanged: (value) {
                  ref.read(currentMoodScoreProvider.notifier).state = value.toInt();
                },
              ),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('😢 Very Bad', style: theme.textTheme.bodySmall),
                Text('😊 Great', style: theme.textTheme.bodySmall),
              ],
            ),
            const SizedBox(height: 32),
            
            // Tags section
            Text(
              'Add tags (optional)',
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: _availableTags.map((tag) {
                final isSelected = selectedTags.contains(tag);
                return FilterChip(
                  label: Text(
                    tag,
                    style: TextStyle(
                      color: isSelected 
                        ? theme.colorScheme.onPrimary 
                        : theme.colorScheme.onSurface,
                      fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                    ),
                  ),
                  selected: isSelected,
                  selectedColor: theme.colorScheme.primary,
                  backgroundColor: theme.colorScheme.surfaceVariant,
                  checkmarkColor: theme.colorScheme.onPrimary,
                  onSelected: (selected) {
                    final newTags = List<String>.from(selectedTags);
                    if (selected) {
                      newTags.add(tag);
                    } else {
                      newTags.remove(tag);
                    }
                    ref.read(currentMoodTagsProvider.notifier).state = newTags;
                  },
                );
              }).toList(),
            ),
            const SizedBox(height: 32),
            
            // Notes section
            Text(
              'Add a note (optional)',
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _noteController,
              maxLines: 4,
              maxLength: 500,
              decoration: InputDecoration(
                hintText: 'What\'s on your mind?',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(color: theme.colorScheme.outline),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(color: theme.colorScheme.outline),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(color: theme.colorScheme.primary, width: 2),
                ),
                filled: true,
                fillColor: theme.colorScheme.surfaceVariant.withOpacity(0.3),
              ),
            ),
            const SizedBox(height: 32),
            
            // Save button
            SizedBox(
              height: 56,
              child: FilledButton.icon(
                onPressed: _saveMoodLog,
                icon: const Icon(Icons.check_circle_rounded, size: 24),
                label: const Text(
                  'Save Mood Log',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.w600,
                    letterSpacing: 0.5,
                  ),
                ),
                style: FilledButton.styleFrom(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                  elevation: 2,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  String _getMoodEmoji(int score) {
    switch (score) {
      case 1:
        return '😢';
      case 2:
        return '😕';
      case 3:
        return '😐';
      case 4:
        return '🙂';
      case 5:
        return '😊';
      default:
        return '😐';
    }
  }

  String _getMoodLabel(int score) {
    switch (score) {
      case 1:
        return 'Very Bad';
      case 2:
        return 'Bad';
      case 3:
        return 'Okay';
      case 4:
        return 'Good';
      case 5:
        return 'Great';
      default:
        return 'Okay';
    }
  }

  Color _getMoodColor(int score, ThemeData theme) {
    switch (score) {
      case 1:
      case 2:
        return Colors.red;
      case 3:
        return Colors.orange;
      case 4:
      case 5:
        return Colors.green;
      default:
        return theme.colorScheme.primary;
    }
  }
}
