import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../providers/auth_provider.dart';
import '../../providers/mood_provider.dart';
import '../../providers/user_provider.dart';
import '../../../domain/entities/mood_log.dart';

class MoodCheckInScreen extends ConsumerStatefulWidget {
  const MoodCheckInScreen({super.key});

  @override
  ConsumerState<MoodCheckInScreen> createState() => _MoodCheckInScreenState();
}

class _MoodCheckInScreenState extends ConsumerState<MoodCheckInScreen> {
  final _noteController = TextEditingController();
  final List<String> _availableTags = [
    'Anxious',
    'Stressed',
    'Calm',
    'Happy',
    'Sad',
    'Energetic',
    'Tired',
    'Grateful',
    'Overwhelmed',
    'Peaceful',
  ];

  @override
  void dispose() {
    _noteController.dispose();
    super.dispose();
  }

  Future<void> _saveMoodLog() async {
    final userId = ref.read(currentUserIdProvider);
    if (userId == null) return;

    final moodScore = ref.read(currentMoodScoreProvider);
    final tags = ref.read(currentMoodTagsProvider);
    final note = _noteController.text.trim();

    final moodLog = MoodLog(
      id: '', // Will be generated by Firestore
      userId: userId,
      moodScore: moodScore,
      createdAt: DateTime.now(),
      tags: tags,
      note: note.isNotEmpty ? note : null,
      source: 'manual',
    );

    try {
      await ref.read(moodNotifierProvider.notifier).createMoodLog(moodLog);
      
      // Update user streak and check-in count
      await ref.read(userNotifierProvider.notifier).incrementTotalCheckIns(userId);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Row(
              children: [
                Icon(Icons.check_circle_rounded, color: Colors.white),
                SizedBox(width: 12),
                Text('Mood logged successfully!'),
              ],
            ),
            backgroundColor: Theme.of(context).colorScheme.tertiary,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            duration: const Duration(seconds: 2),
          ),
        );
        
        // Reset form
        ref.read(currentMoodScoreProvider.notifier).state = 3;
        ref.read(currentMoodTagsProvider.notifier).state = [];
        ref.read(currentMoodNoteProvider.notifier).state = '';
        _noteController.clear();
        
        // Go back
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.error_rounded, color: Colors.white),
                const SizedBox(width: 12),
                Expanded(child: Text('Error logging mood: $e')),
              ],
            ),
            backgroundColor: Theme.of(context).colorScheme.error,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final moodScore = ref.watch(currentMoodScoreProvider);
    final selectedTags = ref.watch(currentMoodTagsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('How are you feeling?'),
        leading: IconButton(
          icon: const Icon(Icons.close_rounded),
          onPressed: () => context.pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Enhanced mood emoji display with glow effect
            Container(
              padding: const EdgeInsets.symmetric(vertical: 40, horizontal: 24),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    _getMoodColor(moodScore).withOpacity(0.12),
                    _getMoodColor(moodScore).withOpacity(0.04),
                  ],
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                ),
                borderRadius: BorderRadius.circular(24),
                boxShadow: [
                  BoxShadow(
                    color: _getMoodColor(moodScore).withOpacity(0.15),
                    blurRadius: 24,
                    offset: const Offset(0, 8),
                  ),
                ],
              ),
              child: Column(
                children: [
                  // Larger emoji with glow effect
                  Container(
                    padding: const EdgeInsets.all(20),
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Colors.white.withOpacity(0.5),
                      boxShadow: [
                        BoxShadow(
                          color: _getMoodColor(moodScore).withOpacity(0.2),
                          blurRadius: 32,
                        ),
                      ],
                    ),
                    child: Text(
                      _getMoodEmoji(moodScore),
                      style: const TextStyle(fontSize: 120),
                    ),
                  ),
                  const SizedBox(height: 20),
                  Text(
                    _getMoodLabel(moodScore),
                    style: theme.textTheme.headlineSmall?.copyWith(
                      fontWeight: FontWeight.w700,
                      color: _getMoodColor(moodScore),
                      letterSpacing: -0.5,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 40),
            
            // Visual Mood Selector Grid (replacing slider)
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: theme.colorScheme.surfaceContainerHighest.withOpacity(0.3),
                borderRadius: BorderRadius.circular(20),
                border: Border.all(
                  color: theme.colorScheme.outline.withOpacity(0.1),
                  width: 1.5,
                ),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Select your mood',
                    style: theme.textTheme.titleLarge?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 16),
                  Wrap(
                    spacing: 12,
                    runSpacing: 12,
                    children: [5, 4, 3, 2, 1].map((score) {
                      final isSelected = moodScore == score;
                      final color = _getMoodColor(score);
                      
                      return GestureDetector(
                        onTap: () {
                          ref.read(currentMoodScoreProvider.notifier).state = score;
                        },
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 200),
                          width: 90,
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          decoration: BoxDecoration(
                            gradient: isSelected
                                ? LinearGradient(
                                    colors: [color, color.withOpacity(0.8)],
                                  )
                                : null,
                            color: isSelected ? null : color.withOpacity(0.12),
                            borderRadius: BorderRadius.circular(18),
                            border: Border.all(
                              color: isSelected ? color : color.withOpacity(0.3),
                              width: isSelected ? 3 : 1.5,
                            ),
                            boxShadow: isSelected
                                ? [
                                    BoxShadow(
                                      color: color.withOpacity(0.3),
                                      blurRadius: 12,
                                      offset: const Offset(0, 4),
                                    ),
                                  ]
                                : null,
                          ),
                          child: Column(
                            children: [
                              Text(
                                _getMoodEmoji(score),
                                style: TextStyle(fontSize: isSelected ? 44 : 36),
                              ),
                              const SizedBox(height: 6),
                              Text(
                                _getMoodLabel(score),
                                style: theme.textTheme.labelMedium?.copyWith(
                                  color: isSelected ? Colors.white : color,
                                  fontWeight: isSelected ? FontWeight.w700 : FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                        ),
                      );
                    }).toList(),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 40),
            
            // Tags section - pill-shaped chips
            Text(
              'Add tags (optional)',
              style: theme.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 16),
            Wrap(
              spacing: 10,
              runSpacing: 10,
              children: _availableTags.map((tag) {
                final isSelected = selectedTags.contains(tag);
                return AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  child: FilterChip(
                    label: Text(
                      tag,
                      style: TextStyle(
                        color: isSelected 
                          ? Colors.white
                          : theme.colorScheme.onSurface,
                        fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500,
                        fontSize: 15,
                      ),
                    ),
                    selected: isSelected,
                    selectedColor: theme.colorScheme.primary,
                    backgroundColor: theme.colorScheme.surfaceContainerHighest,
                    checkmarkColor: Colors.white,
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                    side: BorderSide(
                      color: isSelected
                          ? theme.colorScheme.primary
                          : theme.colorScheme.outline.withOpacity(0.2),
                      width: 1.5,
                    ),
                    onSelected: (selected) {
                      final newTags = List<String>.from(selectedTags);
                      if (selected) {
                        newTags.add(tag);
                      } else {
                        newTags.remove(tag);
                      }
                      ref.read(currentMoodTagsProvider.notifier).state = newTags;
                    },
                  ),
                );
              }).toList(),
            ),
            const SizedBox(height: 40),
            
            // Notes section
            Text(
              'Add a note (optional)',
              style: theme.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _noteController,
              maxLines: 5,
              maxLength: 500,
              style: theme.textTheme.bodyLarge,
              decoration: InputDecoration(
                hintText: 'What\'s on your mind? Share your thoughts or feelings...',
                hintStyle: theme.textTheme.bodyMedium?.copyWith(
                  color: theme.colorScheme.onSurface.withOpacity(0.5),
                ),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(16),
                  borderSide: BorderSide(
                    color: theme.colorScheme.outline.withOpacity(0.3),
                    width: 1.5,
                  ),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(16),
                  borderSide: BorderSide(
                    color: theme.colorScheme.outline.withOpacity(0.3),
                    width: 1.5,
                  ),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(16),
                  borderSide: BorderSide(
                    color: theme.colorScheme.primary,
                    width: 2.5,
                  ),
                ),
                filled: true,
                fillColor: theme.colorScheme.surfaceContainerHighest.withOpacity(0.5),
                contentPadding: const EdgeInsets.all(20),
              ),
            ),
            const SizedBox(height: 40),
            
            // Enhanced save button with gradient
            SizedBox(
              height: 60,
              child: FilledButton.icon(
                onPressed: _saveMoodLog,
                icon: const Icon(Icons.check_circle_rounded, size: 26),
                label: const Text(
                  'Save Mood Log',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.w700,
                    letterSpacing: 0.5,
                  ),
                ),
                style: FilledButton.styleFrom(
                  backgroundColor: theme.colorScheme.primary,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                  elevation: 0,
                  shadowColor: theme.colorScheme.primary.withOpacity(0.3),
                ).copyWith(
                  overlayColor: WidgetStateProperty.all(
                    Colors.white.withOpacity(0.1),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  String _getMoodEmoji(int score) {
    switch (score) {
      case 1:
        return '😢';
      case 2:
        return '😕';
      case 3:
        return '😐';
      case 4:
        return '🙂';
      case 5:
        return '😊';
      default:
        return '😐';
    }
  }

  String _getMoodLabel(int score) {
    switch (score) {
      case 1:
        return 'Very Bad';
      case 2:
        return 'Bad';
      case 3:
        return 'Okay';
      case 4:
        return 'Good';
      case 5:
        return 'Great';
      default:
        return 'Okay';
    }
  }

  Color _getMoodColor(int score) {
    switch (score) {
      case 1:
        return const Color(0xFFE07A7A); // Soft red
      case 2:
        return const Color(0xFFF4A574); // Warm orange
      case 3:
        return const Color(0xFFF9C86D); // Golden yellow
      case 4:
        return const Color(0xFF8BC48A); // Gentle green
      case 5:
        return const Color(0xFF7AC29A); // Vibrant green
      default:
        return const Color(0xFFF9C86D);
    }
  }
}
