import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:uuid/uuid.dart';
import '../../providers/auth_provider.dart';
import '../../providers/chat_provider.dart';
import '../../../domain/entities/chat_session.dart';
import '../../../domain/services/cloud_functions_service.dart';

// Provider for Cloud Functions Service
final cloudFunctionsServiceProvider = Provider<CloudFunctionsService>((ref) {
  return CloudFunctionsService();
});

class ChatScreen extends ConsumerStatefulWidget {
  const ChatScreen({super.key});

  @override
  ConsumerState<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends ConsumerState<ChatScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  bool _showScrollToBottom = false;

  @override
  void initState() {
    super.initState();
    _initializeChat();
    _scrollController.addListener(_onScroll);
  }

  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.removeListener(_onScroll);
    _scrollController.dispose();
    super.dispose();
  }

  void _onScroll() {
    // In reversed ListView, position 0 is bottom (latest messages)
    // Show button when scrolled UP (offset > 200 means we're away from bottom)
    final showButton =
        _scrollController.hasClients && _scrollController.offset > 200;
    if (showButton != _showScrollToBottom) {
      setState(() {
        _showScrollToBottom = showButton;
      });
    }
  }

  void _scrollToBottom({bool animate = true}) {
    if (!mounted || !_scrollController.hasClients) return;

    // In reversed ListView, position 0 is the bottom (latest messages)
    if (animate) {
      _scrollController.animateTo(
        0.0,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeOut,
      );
    } else {
      _scrollController.jumpTo(0.0);
    }
  }

  Future<void> _initializeChat() async {
    final userId = ref.read(currentUserIdProvider);
    if (userId == null) return;

    // Check if there's an active session
    final currentSessionId = ref.read(currentSessionIdProvider);
    if (currentSessionId == null) {
      // Delay to avoid modifying provider during build
      await Future.microtask(() async {
        // Create a new session
        final newSession = ChatSession(
          id: '', // Will be generated by Firestore
          userId: userId,
          startedAt: DateTime.now(),
          messageCount: 0,
          messages: const [],
        );

        try {
          final sessionId = await ref
              .read(chatNotifierProvider.notifier)
              .createChatSession(newSession);
          ref.read(currentSessionIdProvider.notifier).state = sessionId;
        } catch (e) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Error creating chat session: $e')),
            );
          }
        }
      });
    }
  }

  /// Check if device has network connectivity using connectivity_plus
  Future<bool> _checkNetworkConnection() async {
    try {
      // Use connectivity_plus for reliable network detection
      final connectivityResult = await Connectivity().checkConnectivity();
      print('[ChatScreen] Connectivity result: $connectivityResult');

      // Check if we have any network connection
      if (connectivityResult.contains(ConnectivityResult.none)) {
        print('[ChatScreen] No network connection detected');
        return false;
      }

      // We have some form of connectivity (wifi, mobile, ethernet, etc.)
      // Now verify we can actually reach the internet
      try {
        final result = await InternetAddress.lookup(
          'google.com',
        ).timeout(const Duration(seconds: 3));
        if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
          print('[ChatScreen] Network check passed - internet reachable');
          return true;
        }
      } catch (e) {
        print('[ChatScreen] DNS lookup failed: $e');
        // Even if DNS fails, we might still have connectivity
        // Return true if connectivity_plus says we have a connection
        return !connectivityResult.contains(ConnectivityResult.none);
      }

      return true;
    } catch (e) {
      print('[ChatScreen] Network check error: $e');
      return false;
    }
  }

  Future<void> _sendMessage() async {
    final text = _messageController.text.trim();
    if (text.isEmpty) return;

    final userId = ref.read(currentUserIdProvider);
    final sessionId = ref.read(currentSessionIdProvider);

    if (userId == null || sessionId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Session not ready. Please try again.')),
      );
      return;
    }

    // Clear input immediately
    _messageController.clear();

    // Generate a unique ID for tracking this message
    final messageId = const Uuid().v4();

    await _sendMessageInternal(
      messageId: messageId,
      text: text,
      userId: userId,
      sessionId: sessionId,
    );
  }

  /// Retry a failed message
  Future<void> _retryMessage(String messageId) async {
    final failedMessage = ref
        .read(failedMessagesProvider.notifier)
        .getFailedMessage(messageId);
    if (failedMessage == null) return;

    // Remove from failed messages
    ref.read(failedMessagesProvider.notifier).removeFailedMessage(messageId);

    await _sendMessageInternal(
      messageId: messageId,
      text: failedMessage.content,
      userId: failedMessage.userId,
      sessionId: failedMessage.sessionId,
      isRetry: true,
    );
  }

  /// Internal method to send a message (used by both send and retry)
  Future<void> _sendMessageInternal({
    required String messageId,
    required String text,
    required String userId,
    required String sessionId,
    bool isRetry = false,
  }) async {
    // Check network FIRST before doing anything
    final hasNetwork = await _checkNetworkConnection();
    if (!hasNetwork) {
      // Add to failed messages immediately
      ref
          .read(failedMessagesProvider.notifier)
          .addFailedMessage(
            FailedMessage(
              id: messageId,
              content: text,
              timestamp: DateTime.now(),
              sessionId: sessionId,
              userId: userId,
            ),
          );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Row(
              children: [
                Icon(Icons.wifi_off_rounded, color: Colors.white, size: 20),
                SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'No internet connection. Message saved for retry.',
                    style: TextStyle(color: Colors.white),
                  ),
                ),
              ],
            ),
            backgroundColor: Theme.of(context).colorScheme.error,
            action: SnackBarAction(
              label: 'Retry',
              textColor: Colors.white,
              onPressed: () => _retryMessage(messageId),
            ),
            duration: const Duration(seconds: 6),
          ),
        );
      }
      return;
    }

    // Create user message
    final userMessage = ChatMessage(
      id: messageId,
      role: 'user',
      content: text,
      timestamp: DateTime.now(),
      sendStatus: MessageSendStatus.sending,
    );

    // Save user message immediately to Firestore for instant display (only if not retry)
    if (!isRetry) {
      try {
        await ref
            .read(chatRepositoryProvider)
            .addMessageToSession(sessionId: sessionId, message: userMessage);
      } catch (e) {
        print('Error saving user message: $e');
      }
    }

    // Set loading state for AI response
    ref.read(chatLoadingProvider.notifier).state = true;

    try {
      // Use current session messages for context (already in memory)
      final sessionAsync = ref.read(chatSessionStreamProvider(sessionId));
      final conversationHistory = sessionAsync.value?.messages ?? [];

      // Call Cloud Function to get AI response (it will save both messages to Firestore)
      final cloudFunctions = ref.read(cloudFunctionsServiceProvider);
      final aiResult = await cloudFunctions.sendChatMessage(
        userId: userId,
        sessionId: sessionId,
        message: text,
        conversationHistory: conversationHistory,
      );

      // Show crisis warning if detected
      if (aiResult.isCrisis && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text(
              '⚠️ Crisis resources have been shared. Your safety is important.',
            ),
            backgroundColor: Theme.of(context).colorScheme.error,
            duration: const Duration(seconds: 5),
          ),
        );
      }
    } catch (e) {
      // Add to failed messages for retry
      ref
          .read(failedMessagesProvider.notifier)
          .addFailedMessage(
            FailedMessage(
              id: messageId,
              content: text,
              timestamp: DateTime.now(),
              sessionId: sessionId,
              userId: userId,
            ),
          );

      if (mounted) {
        // Determine error message based on exception type
        String errorMessage;
        IconData errorIcon;

        if (e is NetworkException) {
          errorMessage = e.message;
          errorIcon = Icons.wifi_off_rounded;
        } else if (e is AIServiceException) {
          errorMessage = e.message;
          errorIcon = Icons.cloud_off_rounded;
        } else {
          errorMessage = 'Failed to send message. Please try again.';
          errorIcon = Icons.error_outline_rounded;
        }

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                Icon(errorIcon, color: Colors.white, size: 20),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    errorMessage,
                    style: const TextStyle(color: Colors.white),
                  ),
                ),
              ],
            ),
            backgroundColor: Theme.of(context).colorScheme.error,
            action: SnackBarAction(
              label: 'Retry',
              textColor: Colors.white,
              onPressed: () => _retryMessage(messageId),
            ),
            duration: const Duration(seconds: 6),
          ),
        );
      }
    } finally {
      ref.read(chatLoadingProvider.notifier).state = false;
    }
  }

  Future<void> _endSession() async {
    final sessionId = ref.read(currentSessionIdProvider);
    if (sessionId == null) return;

    final confirm = await showDialog<bool>(
      context: context,
      builder:
          (context) => AlertDialog(
            title: const Text('End Conversation'),
            content: const Text(
              'Are you sure you want to end this conversation?',
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context, false),
                child: const Text('Cancel'),
              ),
              FilledButton(
                onPressed: () => Navigator.pop(context, true),
                child: const Text('End'),
              ),
            ],
          ),
    );

    if (confirm == true) {
      try {
        await ref
            .read(chatNotifierProvider.notifier)
            .endChatSession(sessionId: sessionId);
        ref.read(currentSessionIdProvider.notifier).state = null;
        if (mounted) {
          context.pop();
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error ending session: $e')));
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final sessionId = ref.watch(currentSessionIdProvider);
    final isLoading = ref.watch(chatLoadingProvider);

    if (sessionId == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Chat')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    final sessionAsync = ref.watch(chatSessionStreamProvider(sessionId));

    return Scaffold(
      appBar: AppBar(
        title: const Text('MindMate AI Chat'),
        actions: [
          IconButton(
            icon: const Icon(Icons.stop_circle_outlined),
            onPressed: _endSession,
            tooltip: 'End Conversation',
          ),
        ],
      ),
      body: Stack(
        children: [
          Column(
            children: [
              // Messages list
              Expanded(
                child: sessionAsync.when(
                  loading:
                      () => const Center(child: CircularProgressIndicator()),
                  error:
                      (error, stack) => Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(
                              Icons.error_outline,
                              size: 64,
                              color: Colors.red,
                            ),
                            const SizedBox(height: 16),
                            Text('Error: $error'),
                          ],
                        ),
                      ),
                  data: (session) {
                    final messages = session.messages;

                    if (messages.isEmpty) {
                      return Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(
                              Icons.chat_bubble_outline,
                              size: 80,
                              color: Colors.grey,
                            ),
                            const SizedBox(height: 16),
                            Text(
                              'Start a conversation',
                              style: theme.textTheme.titleLarge?.copyWith(
                                color: Colors.grey,
                              ),
                            ),
                            const SizedBox(height: 8),
                            const Padding(
                              padding: EdgeInsets.symmetric(horizontal: 48.0),
                              child: Text(
                                'Share what\'s on your mind. I\'m here to listen and support you.',
                                textAlign: TextAlign.center,
                                style: TextStyle(color: Colors.grey),
                              ),
                            ),
                          ],
                        ),
                      );
                    }

                    // Reversed ListView - automatically shows bottom (latest messages) first
                    // Index 0 = latest message (at bottom), so we reverse the display order
                    final totalItems = messages.length + (isLoading ? 1 : 0);

                    // For few messages, use Column at top; for many, use reversed ListView at bottom
                    if (totalItems <= 5) {
                      // Few messages - show at top of screen
                      return SingleChildScrollView(
                        controller: _scrollController,
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            ...messages.map(
                              (message) => _MessageBubble(
                                message: message,
                                onRetry: () => _retryMessage(message.id),
                              ),
                            ),
                            if (isLoading) _TypingIndicatorBubble(),
                          ],
                        ),
                      );
                    }

                    // Many messages - use reversed ListView (latest at bottom)
                    return ListView.builder(
                      controller: _scrollController,
                      reverse: true,
                      padding: const EdgeInsets.all(16.0),
                      itemCount: totalItems,
                      itemBuilder: (context, index) {
                        // In reversed list: index 0 is at bottom
                        // Typing indicator should be at bottom (index 0)
                        if (isLoading && index == 0) {
                          return _TypingIndicatorBubble();
                        }
                        // Adjust index for messages when loading indicator is shown
                        final messageIndex = isLoading ? index - 1 : index;
                        // Reverse the message order so newest appears at index 0
                        final actualIndex = messages.length - 1 - messageIndex;
                        if (actualIndex < 0 || actualIndex >= messages.length)
                          return const SizedBox();
                        final message = messages[actualIndex];
                        return _MessageBubble(
                          message: message,
                          onRetry: () => _retryMessage(message.id),
                        );
                      },
                    );
                  },
                ),
              ),

              // Message input
              Container(
                decoration: BoxDecoration(
                  color: theme.colorScheme.surface,
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.1),
                      blurRadius: 4,
                      offset: const Offset(0, -2),
                    ),
                  ],
                ),
                padding: const EdgeInsets.symmetric(
                  horizontal: 16.0,
                  vertical: 12.0,
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: TextField(
                        controller: _messageController,
                        decoration: InputDecoration(
                          hintText: 'Type your message...',
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(24),
                          ),
                          contentPadding: const EdgeInsets.symmetric(
                            horizontal: 20,
                            vertical: 12,
                          ),
                        ),
                        maxLines: null,
                        textCapitalization: TextCapitalization.sentences,
                        onSubmitted: (_) => _sendMessage(),
                      ),
                    ),
                    const SizedBox(width: 12),
                    FloatingActionButton(
                      onPressed: isLoading ? null : _sendMessage,
                      mini: true,
                      child: const Icon(Icons.send_rounded),
                    ),
                  ],
                ),
              ),
            ],
          ),

          // Scroll to bottom button
          if (_showScrollToBottom)
            Positioned(
              right: 16,
              bottom: 80,
              child: FloatingActionButton.small(
                onPressed: _scrollToBottom,
                backgroundColor: theme.colorScheme.primary,
                child: Icon(
                  Icons.arrow_downward_rounded,
                  color: theme.colorScheme.onPrimary,
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _MessageBubble extends ConsumerWidget {
  final ChatMessage message;
  final VoidCallback? onRetry;

  const _MessageBubble({required this.message, this.onRetry});

  /// Check if the AI response contains crisis resources
  bool _containsCrisisResources(String content) {
    final lowerContent = content.toLowerCase();
    final crisisIndicators = [
      'crisis',
      'suicide prevention',
      'hotline',
      'emergency:',
      '988',
      '110',
      '119',
      '911',
      'lifeline',
      'immediate support',
      'reach out to',
      'crisis text line',
      'mental health crisis',
    ];
    return crisisIndicators.any(
      (indicator) => lowerContent.contains(indicator),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final isUser = message.role == 'user';
    final timeFormat = DateFormat('h:mm a');
    final isCrisisResponse =
        !isUser && _containsCrisisResources(message.content);

    // Check if this message failed to send
    final failedMessages = ref.watch(failedMessagesProvider);
    final isFailed = isUser && failedMessages.any((m) => m.id == message.id);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Column(
        crossAxisAlignment:
            isUser ? CrossAxisAlignment.end : CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment:
                isUser ? MainAxisAlignment.end : MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              if (!isUser) ...[
                Container(
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    gradient: LinearGradient(
                      colors: [
                        theme.colorScheme.secondary,
                        theme.colorScheme.secondary.withOpacity(0.7),
                      ],
                    ),
                  ),
                  child: CircleAvatar(
                    backgroundColor: Colors.transparent,
                    child: Icon(
                      Icons.psychology_rounded,
                      color: Colors.white,
                      size: 22,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
              ],
              Flexible(
                child: Column(
                  crossAxisAlignment:
                      isUser
                          ? CrossAxisAlignment.end
                          : CrossAxisAlignment.start,
                  children: [
                    ConstrainedBox(
                      constraints: BoxConstraints(
                        maxWidth: MediaQuery.of(context).size.width * 0.75,
                      ),
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 16,
                          vertical: 12,
                        ),
                        decoration: BoxDecoration(
                          gradient:
                              isUser
                                  ? LinearGradient(
                                    colors: [
                                      theme.colorScheme.primary,
                                      theme.colorScheme.primary.withOpacity(
                                        0.8,
                                      ),
                                    ],
                                    begin: Alignment.topLeft,
                                    end: Alignment.bottomRight,
                                  )
                                  : null,
                          color: isUser ? null : Colors.grey[100],
                          borderRadius: BorderRadius.only(
                            topLeft: const Radius.circular(20),
                            topRight: const Radius.circular(20),
                            bottomLeft: Radius.circular(isUser ? 20 : 4),
                            bottomRight: Radius.circular(isUser ? 4 : 20),
                          ),
                          boxShadow: [
                            BoxShadow(
                              color: Colors.black.withOpacity(0.05),
                              blurRadius: 4,
                              offset: const Offset(0, 2),
                            ),
                          ],
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            if (isUser)
                              SelectableText(
                                message.content,
                                style: theme.textTheme.bodyLarge?.copyWith(
                                  color: Colors.white,
                                  height: 1.4,
                                ),
                              )
                            else
                              MarkdownBody(
                                data: message.content,
                                selectable: true,
                                styleSheet: MarkdownStyleSheet(
                                  p: theme.textTheme.bodyLarge?.copyWith(
                                    color: Colors.grey[900],
                                    height: 1.4,
                                  ),
                                  listBullet: theme.textTheme.bodyLarge
                                      ?.copyWith(color: Colors.grey[900]),
                                ),
                              ),
                            if (message.safetyFlagged) ...[
                              const SizedBox(height: 8),
                              Container(
                                padding: const EdgeInsets.all(8),
                                decoration: BoxDecoration(
                                  color: Colors.red.withOpacity(0.1),
                                  borderRadius: BorderRadius.circular(8),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    const Icon(
                                      Icons.warning_amber_rounded,
                                      size: 16,
                                      color: Colors.red,
                                    ),
                                    const SizedBox(width: 4),
                                    Flexible(
                                      child: Text(
                                        'Crisis keywords detected',
                                        style: theme.textTheme.bodySmall
                                            ?.copyWith(
                                              color: Colors.red,
                                              fontWeight: FontWeight.w600,
                                            ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 4),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 4),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(
                            timeFormat.format(message.timestamp),
                            style: theme.textTheme.bodySmall?.copyWith(
                              color:
                                  isFailed
                                      ? Colors.red
                                      : theme.colorScheme.onSurfaceVariant
                                          .withOpacity(0.6),
                              fontSize: 11,
                            ),
                          ),
                          if (isFailed) ...[
                            const SizedBox(width: 8),
                            Icon(
                              Icons.error_outline_rounded,
                              size: 14,
                              color: Colors.red,
                            ),
                            const SizedBox(width: 4),
                            GestureDetector(
                              onTap: onRetry,
                              child: Text(
                                'Failed · Tap to retry',
                                style: theme.textTheme.bodySmall?.copyWith(
                                  color: Colors.red,
                                  fontWeight: FontWeight.w600,
                                  fontSize: 11,
                                ),
                              ),
                            ),
                          ],
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              if (isUser) ...[
                const SizedBox(width: 8),
                CircleAvatar(
                  backgroundColor: theme.colorScheme.primary.withOpacity(0.2),
                  child: Icon(
                    Icons.person_rounded,
                    color: theme.colorScheme.primary,
                  ),
                ),
              ],
            ],
          ),
          // Crisis warning banner for AI responses with crisis resources
          if (isCrisisResponse) ...[
            const SizedBox(height: 8),
            Container(
              margin: const EdgeInsets.only(left: 48),
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.red.shade50,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.red.shade200, width: 1),
              ),
              child: Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: Colors.red.shade100,
                      shape: BoxShape.circle,
                    ),
                    child: Icon(
                      Icons.health_and_safety_rounded,
                      color: Colors.red.shade700,
                      size: 20,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Help is Available',
                          style: theme.textTheme.titleSmall?.copyWith(
                            color: Colors.red.shade800,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          'You are not alone. Please reach out to the resources above if you need support.',
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: Colors.red.shade700,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}

// Animated typing indicator widget
class _TypingIndicator extends StatefulWidget {
  const _TypingIndicator();

  @override
  State<_TypingIndicator> createState() => _TypingIndicatorState();
}

class _TypingIndicatorState extends State<_TypingIndicator>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      duration: const Duration(milliseconds: 1200),
      vsync: this,
    )..repeat();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: List.generate(3, (index) {
        return AnimatedBuilder(
          animation: _controller,
          builder: (context, child) {
            final delay = index * 0.2;
            final value = (_controller.value - delay).clamp(0.0, 1.0);
            final opacity = (math.sin(value * math.pi) * 0.6 + 0.4);
            final scale = (math.sin(value * math.pi) * 0.3 + 0.7);

            return Transform.scale(
              scale: scale,
              child: Opacity(
                opacity: opacity,
                child: Container(
                  margin: EdgeInsets.only(right: index < 2 ? 6 : 0),
                  width: 8,
                  height: 8,
                  decoration: BoxDecoration(
                    color: Colors.grey[600],
                    shape: BoxShape.circle,
                  ),
                ),
              ),
            );
          },
        );
      }),
    );
  }
}

// Typing indicator as a message bubble
class _TypingIndicatorBubble extends StatelessWidget {
  const _TypingIndicatorBubble();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: LinearGradient(
                colors: [
                  theme.colorScheme.secondary,
                  theme.colorScheme.secondary.withOpacity(0.7),
                ],
              ),
            ),
            child: CircleAvatar(
              backgroundColor: Colors.transparent,
              child: const Icon(
                Icons.psychology_rounded,
                color: Colors.white,
                size: 22,
              ),
            ),
          ),
          const SizedBox(width: 8),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: Colors.grey[100],
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(20),
                topRight: Radius.circular(20),
                bottomLeft: Radius.circular(4),
                bottomRight: Radius.circular(20),
              ),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.05),
                  blurRadius: 4,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: _TypingIndicator(),
          ),
        ],
      ),
    );
  }
}
